import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../(index)/globals.css";
import Header from "../../components/layout/Header";
import Footer from "../../components/layout/Footer";
import React from "react";
import { Providers } from "@/app/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let loggedIn = true;
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <Header loggedIn={loggedIn} />
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
